package fr.alb.api;

import java.io.InputStream;
import java.time.Instant;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;
import java.util.HashMap;
import java.util.Map;

import fr.alb.dto.ErrorResponse;
import fr.alb.billing.model.Invoice;
import fr.alb.billing.model.InvoiceTemplate;
import fr.alb.billing.service.TemplateRenderer;
import fr.alb.billing.service.PdfService;
import jakarta.annotation.security.RolesAllowed;
import jakarta.inject.Inject;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import org.eclipse.microprofile.openapi.annotations.Operation;
import org.eclipse.microprofile.openapi.annotations.media.Content;
import org.eclipse.microprofile.openapi.annotations.media.Schema;
import org.eclipse.microprofile.openapi.annotations.parameters.Parameter;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponse;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponses;
import org.eclipse.microprofile.openapi.annotations.tags.Tag;
import io.quarkus.logging.Log;

@Path("/invoice-templates")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
@Tag(name = "Invoice Templates", description = "Operations related to invoice template management")
public class InvoiceTemplateResource {

    @Inject TemplateRenderer renderer;
    @Inject PdfService pdfService;

    @GET
    @Operation(summary = "List all invoice templates", description = "Retrieve a list of all invoice templates")
    @APIResponse(responseCode = "200", description = "List of templates retrieved successfully")
    public List<TemplateSummary> list() {
        List<InvoiceTemplate> templates = InvoiceTemplate.listAll();
        return templates.stream()
                .map(t -> new TemplateSummary(
                        t.id != null ? t.id : "",
                        t.name != null ? t.name : "",
                        t.status != null ? t.status : "active",
                        t.type != null ? t.type : "final",
                        t.updatedAt,
                        t.version != null ? t.version : 1,
                        generateThumbnailUrl(t.id != null ? t.id : "")
                ))
                .collect(Collectors.toList());
    }

    @GET
    @Path("{id}")
    @Operation(summary = "Get template by ID", description = "Retrieve a specific invoice template by its ID")
    @APIResponses({
            @APIResponse(responseCode = "200", description = "Template found"),
            @APIResponse(responseCode = "404", description = "Template not found")
    })
    public InvoiceTemplate get(
            @Parameter(description = "Template ID", required = true)
            @PathParam("id") String id) {

        InvoiceTemplate tpl = InvoiceTemplate.findByIdWithInit(id);
        if (tpl == null) {
            throw new NotFoundException("Template with id " + id + " not found");
        }
        return tpl;
    }

    @POST
    @Operation(summary = "Create new template", description = "Create a new invoice template")
    @APIResponses({
            @APIResponse(responseCode = "201", description = "Template created successfully"),
            @APIResponse(responseCode = "400", description = "Invalid template data"),
            @APIResponse(responseCode = "403", description = "Insufficient permissions")
    })
    @RolesAllowed("ROLE_TEMPLATES_ADMIN")
    public Response create(@Valid TemplateRequest request) {
        // Validation
        if (request.name == null || request.name.trim().isEmpty()) {
            return Response.status(Response.Status.BAD_REQUEST)
                    .entity(new ErrorResponse("BAD_REQUEST", "Template name is required", 400))
                    .build();
        }

        // Création du template
        InvoiceTemplate tpl = new InvoiceTemplate();
        // ID is automatically generated by InvoiceTemplate constructor
        tpl.name = request.name;
        tpl.status = request.status != null ? request.status : "active";
        // Type is set at creation only, then immutable. Default 'final' for back-compat.
        String requestedType = request.type != null ? request.type.toLowerCase() : "final";
        if (!"draft".equals(requestedType) && !"final".equals(requestedType)) {
            return Response.status(Response.Status.BAD_REQUEST)
                    .entity(new ErrorResponse("BAD_REQUEST", "type must be 'draft' or 'final'", 400))
                    .build();
        }
        tpl.type = requestedType;
        tpl.bindings = request.bindings != null ? request.bindings : new HashMap<>();
        tpl.pageSettings = request.pageSettings != null ? request.pageSettings : new InvoiceTemplate.PageSettings();
        // Accept either nested `template` or legacy top-level `html`/`css` (resolvedContent merges them).
        InvoiceTemplate.TemplateContent resolved = request.resolvedContent();
        tpl.template = resolved != null ? resolved : new InvoiceTemplate.TemplateContent();
        tpl.expressDesignId = request.expressDesignId;
        tpl.createdAt = Instant.now();
        tpl.updatedAt = tpl.createdAt;
        tpl.version = 1;

        tpl.persist();

        return Response.status(Response.Status.CREATED).entity(tpl).build();
    }

    @PUT
    @Path("{id}")
    @Operation(summary = "Update template", description = "Update an existing invoice template")
    @APIResponses({
            @APIResponse(responseCode = "200", description = "Template updated successfully"),
            @APIResponse(responseCode = "404", description = "Template not found"),
            @APIResponse(responseCode = "400", description = "Invalid template data"),
            @APIResponse(responseCode = "403", description = "Insufficient permissions")
    })
    @RolesAllowed("ROLE_TEMPLATES_ADMIN")
    public InvoiceTemplate update(
            @Parameter(description = "Template ID", required = true)
            @PathParam("id") String id,
            @Valid TemplateRequest request) {

        InvoiceTemplate existing = InvoiceTemplate.findById(id);
        if (existing == null) {
            throw new NotFoundException("Template with id " + id + " not found");
        }

        // Mise à jour des champs
        if (request.name != null) existing.name = request.name;
        if (request.status != null) existing.status = request.status;
        if (request.bindings != null) existing.bindings = request.bindings;
        if (request.pageSettings != null) existing.pageSettings = request.pageSettings;
        // Accept either nested `template` or legacy top-level `html`/`css` (resolvedContent merges them).
        InvoiceTemplate.TemplateContent resolvedUpdate = request.resolvedContent();
        if (resolvedUpdate != null) existing.template = resolvedUpdate;
        if (request.expressDesignId != null) existing.expressDesignId = request.expressDesignId;

        existing.updateTimestamp();
        existing.update();

        return existing;
    }

    @POST
    @Path("{id}/activate")
    @Operation(summary = "Activate template",
            description = "Atomically marks this template as the active one for its type, archiving any other previously-active template of the same type.")
    @APIResponses({
            @APIResponse(responseCode = "200", description = "Template activated successfully"),
            @APIResponse(responseCode = "404", description = "Template not found"),
            @APIResponse(responseCode = "403", description = "Insufficient permissions")
    })
    @RolesAllowed("ROLE_TEMPLATES_ADMIN")
    public InvoiceTemplate activate(@PathParam("id") String id) {
        InvoiceTemplate target = InvoiceTemplate.findById(id);
        if (target == null) {
            throw new NotFoundException("Template with id " + id + " not found");
        }
        String type = target.type != null ? target.type : "final";

        // Demote any other currently-active template of the same type.
        List<InvoiceTemplate> others = InvoiceTemplate
                .<InvoiceTemplate>find("status = ?1 and type = ?2 and _id != ?3", "active", type, id)
                .list();
        for (InvoiceTemplate other : others) {
            other.status = "archived";
            other.updateTimestamp();
            other.update();
        }

        // Activate the target.
        target.status = "active";
        target.updateTimestamp();
        target.update();

        Log.infof("[InvoiceTemplate] Activated %s (type=%s); demoted %d others", id, type, others.size());
        return target;
    }

    @DELETE
    @Path("{id}")
    @Operation(summary = "Delete template", description = "Delete an invoice template (or archive it)")
    @APIResponses({
            @APIResponse(responseCode = "204", description = "Template deleted successfully"),
            @APIResponse(responseCode = "404", description = "Template not found"),
            @APIResponse(responseCode = "403", description = "Insufficient permissions")
    })
    @RolesAllowed("ROLE_TEMPLATES_ADMIN")
    public Response delete(
            @Parameter(description = "Template ID", required = true)
            @PathParam("id") String id,
            @QueryParam("archive") @DefaultValue("true") boolean archive) {

        InvoiceTemplate template = InvoiceTemplate.findById(id);
        if (template == null) {
            throw new NotFoundException("Template with id " + id + " not found");
        }

        if (archive) {
            // Archiver au lieu de supprimer
            template.status = "archived";
            template.updateTimestamp();
            template.update();
        } else {
            // Suppression définitive
            template.delete();
        }

        return Response.noContent().build();
    }

    @POST
    @Path("{id}/preview")
    @Operation(summary = "Preview template as PDF", description = "Generate a PDF preview of the template with sample data")
    @APIResponses({
            @APIResponse(responseCode = "200", description = "PDF generated successfully",
                    content = @Content(mediaType = "application/pdf")),
            @APIResponse(responseCode = "404", description = "Template not found"),
            @APIResponse(responseCode = "500", description = "PDF generation failed")
    })
    @Produces("application/pdf")
    @RolesAllowed({"ROLE_TEMPLATES_ADMIN", "ROLE_INVOICES_VIEW"})
    public Response preview(
            @Parameter(description = "Template ID", required = true)
            @PathParam("id") String id,
            PreviewRequest request) {

        InvoiceTemplate tpl = InvoiceTemplate.findById(id);
        if (tpl == null) {
            return Response.status(Response.Status.NOT_FOUND)
                    .entity(new ErrorResponse("NOT_FOUND", "Template not found", 404))
                    .build();
        }

        // Build a sample Invoice for preview rendering
        Invoice sampleInvoice = buildSampleInvoice();

        try {
            String html = renderer.render(tpl, sampleInvoice);
            byte[] pdf = pdfService.htmlToPdf(html);

            return Response.ok(pdf)
                    .header("Content-Disposition", "inline; filename=template-preview-" + id + ".pdf")
                    .header("Content-Type", "application/pdf")
                    .build();
        } catch (Exception e) {
            Log.error("PDF generation failed for template " + id, e);
            return Response.status(Response.Status.INTERNAL_SERVER_ERROR)
                    .entity(new ErrorResponse("INTERNAL_ERROR", "PDF generation failed: " + e.getMessage(), 500))
                    .build();
        }
    }

    // Classes DTO pour les requêtes
    @Schema(description = "Template creation/update request")
    public static class TemplateRequest {
        @Schema(description = "Template name", required = true)
        @NotBlank(message = "Template name is required")
        public String name;

        @Schema(description = "Template status")
        public String status = "active";

        @Schema(description = "Template type — set at creation, ignored on update", enumeration = {"draft", "final"})
        public String type;

        @Schema(description = "Template bindings")
        public Map<String, Object> bindings = new HashMap<>();

        @Schema(description = "Page settings")
        public InvoiceTemplate.PageSettings pageSettings;

        @Schema(description = "Template content (nested form)")
        public InvoiceTemplate.TemplateContent template;

        @Schema(description = "Top-level HTML (legacy/compat form). Merged into template.html if present.")
        public String html;

        @Schema(description = "Top-level CSS (legacy/compat form). Merged into template.css if present.")
        public String css;

        @Schema(description = "Adobe Express design ID")
        public String expressDesignId;

        /**
         * Resolves the template content from either the nested `template` field
         * or the legacy top-level `html`/`css` fields. Frontend currently sends
         * the legacy form; backend accepts both.
         */
        public InvoiceTemplate.TemplateContent resolvedContent() {
            InvoiceTemplate.TemplateContent c = this.template != null
                    ? this.template
                    : new InvoiceTemplate.TemplateContent();
            if ((c.html == null || c.html.isBlank()) && this.html != null && !this.html.isBlank()) {
                c.html = this.html;
            }
            if ((c.css == null || c.css.isBlank()) && this.css != null && !this.css.isBlank()) {
                c.css = this.css;
            }
            // If after merging both are still null/empty, return null so the model field stays null
            // (avoids creating an empty TemplateContent shell on legacy minimal payloads).
            if ((c.html == null || c.html.isBlank()) && (c.css == null || c.css.isBlank())) {
                return null;
            }
            return c;
        }
    }

    @Schema(description = "Preview request with sample data")
    public static class PreviewRequest {
        @Schema(description = "Sample data for template rendering")
        public Map<String, Object> sampleData;

        @Schema(description = "Output format", enumeration = {"pdf", "html"})
        public String format = "pdf";

        @Schema(description = "Preview mode", enumeration = {"draft", "final"})
        public String mode = "draft";
    }

    @Schema(description = "Template summary for listings")
    public static record TemplateSummary(
            @Schema(description = "Template ID") String id,
            @Schema(description = "Template name") String name,
            @Schema(description = "Template status") String status,
            @Schema(description = "Template type — 'draft' or 'final'") String type,
            @Schema(description = "Last update timestamp") Instant updatedAt,
            @Schema(description = "Template version") Integer version,
            @Schema(description = "Thumbnail URL") String thumbnailUrl
    ) {}

    // Méthodes utilitaires privées
    private String generateThumbnailUrl(String templateId) {
        return "/api/invoice-templates/" + templateId + "/thumbnail";
    }

    /**
     * Build a sample Invoice populated with fake data for template preview purposes.
     * Field names mirror those used by TemplateRenderer.buildContext().
     */
    private Invoice buildSampleInvoice() {
        Invoice sample = new Invoice();
        sample.finalNumber = "INV-2025-001";
        sample.draftNumber = "DRF-2025-001";
        sample.status = "FINAL";
        sample.customerName = "Acme Corporation";
        sample.facility = "Port de Marseille";
        sample.currency = "EUR";
        sample.createdDate = java.time.LocalDate.now();
        sample.subtotalAmount = new java.math.BigDecimal("1000.00");
        sample.totalTaxAmount = new java.math.BigDecimal("200.00");
        sample.grandTotalAmount = new java.math.BigDecimal("1200.00");

        fr.alb.billing.model.InvoiceLineSnap line1 = new fr.alb.billing.model.InvoiceLineSnap();
        line1.description = "Prestation de services logistiques";
        line1.quantity = new java.math.BigDecimal("2");
        line1.uom = "unit";
        line1.unitPrice = new java.math.BigDecimal("500.00");
        line1.amount = new java.math.BigDecimal("1000.00");
        line1.currency = "EUR";
        line1.taxTotal = new java.math.BigDecimal("200.00");
        line1.finalAmount = new java.math.BigDecimal("1200.00");

        sample.lines = java.util.List.of(line1);
        return sample;
    }
    // Ajoutez cette méthode dans votre classe InvoiceTemplateResource

    @GET
    @Path("{id}/thumbnail")
    @Operation(summary = "Get template thumbnail", description = "Generate or retrieve a thumbnail image for the template")
    @APIResponses({
            @APIResponse(responseCode = "200", description = "Thumbnail generated successfully",
                    content = @Content(mediaType = "image/png")),
            @APIResponse(responseCode = "404", description = "Template not found"),
            @APIResponse(responseCode = "500", description = "Thumbnail generation failed")
    })
    @Produces("image/png")
    public Response getThumbnail(
            @Parameter(description = "Template ID", required = true)
            @PathParam("id") String id) {

        InvoiceTemplate tpl = InvoiceTemplate.findById(id);
        if (tpl == null) {
            Log.warn("Template not found for thumbnail generation: " + id);
            return Response.status(Response.Status.NOT_FOUND)
                    .entity(new ErrorResponse("NOT_FOUND", "Template not found", 404))
                    .build();
        }

        try {
            // Tentative de génération du thumbnail
            byte[] thumbnail = generateThumbnailForTemplate(tpl);

            return Response.ok(thumbnail)
                    .header("Content-Type", "image/png")
                    .header("Cache-Control", "public, max-age=3600") // Cache 1 heure
                    .header("Content-Disposition", "inline; filename=thumbnail-" + id + ".png")
                    .build();

        } catch (Exception e) {
            Log.error("Thumbnail generation failed for template " + id, e);
            // Retourner une image placeholder en cas d'erreur
            return getPlaceholderThumbnail();
        }
    }

    private byte[] generateThumbnailForTemplate(InvoiceTemplate template) throws Exception {
        // Pour l'instant, on utilise le service PDF existant pour générer le contenu
        Invoice sampleInvoice = buildSampleInvoice();
        String html = renderer.render(template, sampleInvoice);

        // Option 1: Si vous avez une méthode pour convertir HTML en image
        // return pdfService.htmlToThumbnail(html);

        // Option 2: Convertir en PDF puis extraire la première page comme image
        // byte[] pdf = pdfService.htmlToPdf(html);
        // return pdfService.pdfToThumbnail(pdf);

        // Option 3: Pour l'instant, retourner le placeholder
        throw new UnsupportedOperationException("Thumbnail generation not yet implemented");
    }

    private Response getPlaceholderThumbnail() {
        try {
            // Essayer de charger une image placeholder depuis les resources
            InputStream placeholder = getClass().getResourceAsStream("/META-INF/resources/images/template-placeholder.png");
            if (placeholder != null) {
                byte[] imageBytes = placeholder.readAllBytes();
                placeholder.close();

                return Response.ok(imageBytes)
                        .header("Content-Type", "image/png")
                        .header("Cache-Control", "public, max-age=86400") // Cache 24h pour placeholder
                        .build();
            }
        } catch (Exception e) {
            Log.warn("Could not load placeholder image", e);
        }

        // Fallback: générer une image placeholder simple programmatiquement
        return generateSimplePlaceholder();
    }

    private Response generateSimplePlaceholder() {
        try {
            // Créer une image PNG simple de 200x150 pixels
            java.awt.image.BufferedImage image = new java.awt.image.BufferedImage(200, 150, java.awt.image.BufferedImage.TYPE_INT_RGB);
            java.awt.Graphics2D g2d = image.createGraphics();

            // Fond gris clair
            g2d.setColor(java.awt.Color.LIGHT_GRAY);
            g2d.fillRect(0, 0, 200, 150);

            // Bordure
            g2d.setColor(java.awt.Color.DARK_GRAY);
            g2d.drawRect(0, 0, 199, 149);

            // Texte "Template"
            g2d.setColor(java.awt.Color.BLACK);
            g2d.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
            java.awt.FontMetrics fm = g2d.getFontMetrics();
            String text = "Template";
            int x = (200 - fm.stringWidth(text)) / 2;
            int y = (150 + fm.getAscent()) / 2;
            g2d.drawString(text, x, y);

            g2d.dispose();

            // Convertir en bytes
            java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
            javax.imageio.ImageIO.write(image, "PNG", baos);
            byte[] imageBytes = baos.toByteArray();
            baos.close();

            return Response.ok(imageBytes)
                    .header("Content-Type", "image/png")
                    .header("Cache-Control", "public, max-age=86400")
                    .build();

        } catch (Exception e) {
            Log.error("Failed to generate simple placeholder", e);
            // Dernier recours: retourner une réponse vide
            return Response.status(Response.Status.NO_CONTENT).build();
        }
    }
}