package fr.alb.billing.resource;

import fr.alb.common.ValidationUtils;
import fr.alb.common.GenericMapper;
import fr.alb.billing.dao.ContractDao;
import fr.alb.dto.CalculationModeDTO;
import fr.alb.dto.ContractDTO;
import fr.alb.dto.ContractUpdateDTO;
import fr.alb.dto.EventDTO;
import fr.alb.billing.model.Contract;
import fr.alb.yard.model.EventConfig;
import jakarta.annotation.security.RolesAllowed;
import jakarta.inject.Inject;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@Path("contract")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class ContractResource {

        @Inject
        ContractDao contractDao;

        @POST
        @RolesAllowed("ROLE_ADMIN")
        public Response createContract(Contract contract) {
                // Validation centralisée
                ValidationUtils.validateRequired(contract, "contract");
                ValidationUtils.validateNotBlank(contract.name, "contract.name");

                // Validation métier - correction de la syntaxe Java
                if (contract.calculationMode != null &&
                        contract.calculationMode.eventConfig != null &&
                        contract.calculationMode.eventConfig.getId() != null) {

                        ValidationUtils.validateId(contract.calculationMode.eventConfig.getId(), "eventConfig.id");

                        EventConfig evt = EventConfig.findById(contract.calculationMode.eventConfig.getId());
                        if (evt == null) {
                                throw new IllegalArgumentException("Invalid eventConfig.id: event not found");
                        }
                        contract.calculationMode.eventConfig = evt;
                }

                // ID is automatically generated by EntityBase constructor

                contractDao.addContract(contract);
                return Response.status(Response.Status.CREATED)
                        .entity(Map.of("id", contract.getId(), "message", "Contract created"))
                        .build();
        }

        @GET
        @RolesAllowed({"ROLE_ADMIN", "ROLE_USER", "ROLE_READONLY"})
        public List<ContractDTO> getContracts() {
                return contractDao.getContracts().stream()
                        .map(this::toDTO)
                        .toList();
        }

        @GET
        @Path("{contractId}")
        @RolesAllowed({"ROLE_ADMIN", "ROLE_USER", "ROLE_READONLY"})
        public ContractDTO getContract(@PathParam("contractId") String contractId) {
                ValidationUtils.validateId(contractId, "contractId");

                Contract contract = contractDao.findContract(contractId);
                if (contract == null) {
                        throw new NotFoundException();
                }

                return toDTO(contract);
        }

        @PUT
        @Path("{contractId}")
        @RolesAllowed("ROLE_ADMIN")
        public ContractDTO updateContract(@PathParam("contractId") String contractId,
                                          ContractUpdateDTO updateDto) {
                ValidationUtils.validateId(contractId, "contractId");
                ValidationUtils.validateRequired(updateDto, "updateDto");

                Contract existing = contractDao.findContract(contractId);
                if (existing == null) {
                        throw new NotFoundException();
                }

                // Validation métier pour la mise à jour
                if (updateDto.calculationMode != null &&
                        updateDto.calculationMode.eventConfig != null &&
                        updateDto.calculationMode.eventConfig.getId() != null) {

                        ValidationUtils.validateId(updateDto.calculationMode.eventConfig.getId(), "eventConfig.id");

                        EventConfig evt = EventConfig.findById(updateDto.calculationMode.eventConfig.getId());
                        if (evt == null) {
                                throw new IllegalArgumentException("Invalid eventConfig.id: event not found");
                        }
                        updateDto.calculationMode.eventConfig = evt;
                }

                // Mapping automatique des champs basiques
                GenericMapper.mapBasicFields(updateDto, existing);

                contractDao.updateContract(existing);
                return toDTO(existing);
        }

        private ContractDTO toDTO(Contract contract) {
                ContractDTO dto = new ContractDTO();

                // Mapping manuel des champs simples
                dto.id = contract.getId();
                dto.name = contract.name;
                dto.description = contract.description;
                dto.status = contract.status;
                dto.startDate = contract.startDate;
                dto.endDate = contract.endDate;
                dto.rates = contract.rates;
                dto.tariffId = contract.tariffId;
                dto.customerId = contract.customerId;
                dto.customerName = contract.customerName;
                dto.priority = contract.priority;
                dto.addendums = contract.addendums;

                // Mapping complexe pour calculationMode
                if (contract.calculationMode != null) {
                        dto.calculationMode = new CalculationModeDTO();
                        dto.calculationMode.type = contract.calculationMode.type;
                        dto.calculationMode.subType = contract.calculationMode.subType;
                        dto.calculationMode.filters = contract.calculationMode.filters;

                        // Mapping de l'eventConfig
                        if (contract.calculationMode.eventConfig != null &&
                                contract.calculationMode.eventConfig.getId() != null) {

                                EventConfig evt = EventConfig.findById(contract.calculationMode.eventConfig.getId());
                                if (evt != null) {
                                        dto.calculationMode.eventConfig = new EventDTO();
                                        dto.calculationMode.eventConfig.id = evt.getId();
                                        dto.calculationMode.eventConfig.eventName = evt.getEventName();
                                        dto.calculationMode.eventConfig.eventType = evt.getEventType();
                                        dto.calculationMode.eventConfig.billedEvent = evt.isBilledEvent();
                                }
                        }
                }

                return dto;
        }
}

